[package]
name = "ring-signatures"
version = "0.1.0"
authors = ["Jim Posen <jim.posen@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = "1.2.3"
merlin = "1.2.1"
rand_core = "0.4.2"

[dev-dependencies]
rand = "0.6.5"
criterion = "0.3.0"

[[bench]]
name = "bench"
harness = false
